## Internal hosted-effect boundary used by the platform wrappers.
##
## Applications should import `Stdout`, `Stderr`, and `Stdin` instead.
Host := [].{
	stdin_line! : {} => Str
	stdout_line! : Str => {}
	set_timeouts! : U64, U64, U64, U64 => {}
	set_script_timeout_override! : U64 => {}
	set_assert_timeout_override! : U64 => {}
	set_page_load_timeout_override! : U64 => {}
	set_implicit_timeout_override! : U64 => {}
	reset_test_overrides! : {} => {}
	set_window_size! : Str => {}
	set_window_size_override! : Str => {}
	get_assert_timeout! : {} => U64
	wait! : U64 => {}
	get_time_milis! : {} => I64
	is_debug_mode! : {} => I64
	is_verbose! : {} => I64
	reset_test_log_bucket! : {} => {}
	get_logs_from_bucket! : {} => List(Str)
	get_test_name_filter! : {} => Str
	create_dir_if_not_exist! : Str => Try({}, [FileSystemError(Str)])
	file_write_utf8! : Str, Str => Try({}, [FileSystemError(Str)])
	start_session! : {} => Try(Str, [WebDriverError(Str)])
	delete_session! : Str => Try({}, [WebDriverError(Str)])
	browser_navigate_to! : Str, Str => Try({}, [WebDriverError(Str)])
	browser_find_element! : Str, Str, Str => Try(Str, [WebDriverError(Str)])
	browser_find_elements! : Str, Str, Str => Try(List(Str), [WebDriverError(Str)])
	element_click! : Str, Str => Try({}, [WebDriverError(Str)])
	browser_get_screenshot! : Str => Try(Str, [WebDriverError(Str)])
	add_cookie! : Str, Str, Str, Str, Str, Str, I64, I64, I64 => Try({}, [WebDriverError(Str)])
	get_cookie! : Str, Str => Try(List(Str), [WebDriverError(Str)])
	get_all_cookies! : Str => Try(List(List(Str)), [WebDriverError(Str)])
	delete_cookie! : Str, Str => Try({}, [WebDriverError(Str)])
	delete_all_cookies! : Str => Try({}, [WebDriverError(Str)])
	alert_dismiss! : Str => Try({}, [WebDriverError(Str)])
	alert_send_text! : Str, Str => Try({}, [WebDriverError(Str)])
	alert_get_text! : Str => Try(Str, [WebDriverError(Str)])
	alert_accept! : Str => Try({}, [WebDriverError(Str)])
	element_get_text! : Str, Str => Try(Str, [WebDriverError(Str)])
	element_is_selected! : Str, Str => Try(Str, [WebDriverError(Str)])
	element_is_displayed! : Str, Str => Try(Str, [WebDriverError(Str)])
	element_get_attribute! : Str, Str, Str => Try(Str, [WebDriverError(Str)])
	element_get_property! : Str, Str, Str => Try(Str, [WebDriverError(Str)])
	element_send_keys! : Str, Str, Str => Try({}, [WebDriverError(Str)])
	element_clear! : Str, Str => Try({}, [WebDriverError(Str)])
	element_find_element! : Str, Str, Str, Str => Try(Str, [WebDriverError(Str)])
	element_find_elements! : Str, Str, Str, Str => Try(List(Str), [WebDriverError(Str)])
	element_get_tag! : Str, Str => Try(Str, [WebDriverError(Str)])
	element_get_css! : Str, Str, Str => Try(Str, [WebDriverError(Str)])
	element_get_rect! : Str, Str => Try(List(F64), [WebDriverError(Str)])
	browser_set_window_rect! : Str, I64, I64, I64, I64, I64 => Try(List(I64), [WebDriverError(Str)])
	browser_get_window_rect! : Str => Try(List(I64), [WebDriverError(Str)])
	browser_get_title! : Str => Try(Str, [WebDriverError(Str)])
	browser_get_url! : Str => Try(Str, [WebDriverError(Str)])
	browser_reload! : Str => Try({}, [WebDriverError(Str)])
	browser_navigate_back! : Str => Try({}, [WebDriverError(Str)])
	browser_navigate_forward! : Str => Try({}, [WebDriverError(Str)])
	browser_maximize! : Str => Try(List(I64), [WebDriverError(Str)])
	browser_minimize! : Str => Try(List(I64), [WebDriverError(Str)])
	browser_full_screen! : Str => Try(List(I64), [WebDriverError(Str)])
	execute_js! : Str, Str, Str => Try(Str, [WebDriverError(Str)])
	get_env! : Str => Str
	get_page_source! : Str => Try(Str, [WebDriverError(Str)])
	switch_to_frame_by_element_id! : Str, Str => Try({}, [WebDriverError(Str)])
	switch_to_parent_frame! : Str => Try({}, [WebDriverError(Str)])
}
